### PR TITLE
Fix/773 frontend responsiveness complete seedlot register

### LINKED ISSUE #773: Frontend Responsiveness (Complete seedlot register)
Sub-task from [#193](https://github.com/bcgov/nr-spar/issues/193)
Responsiveness a bit broken after recent changes, after some tests some issues were spotted at this screen:

MEDIUM (672px): 
  - [ ]   Not showing step 6
  Image

SMALL (320px):
  - [x]  Register steps should be on vertical
Image
  - [x]  Breadcrumbs should be at same line
  - [x]  Breadcrumb should have a overflow menu when small
Image

### PR DESCRIPTION
**Pull request by ArthurEncr**
# Description
Closes #773 

#### New
- New breadcrumb component: now when using small screens the middle breadcrumb should transform into an overflow menu

#### Changed
- Registration steps vertical on small screens (320px)

#### Removed
- Nothing

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

I still haven't found the solution for the bug related to not showing step 6 on medium screens (672px)

###  What gif/image best describes this PR or how it makes you feel?

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Frontend](https://nr-spar-47-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-47-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-47-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Frontend](https://nr-spar-47-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-47-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-47-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

### CODE REVIEW

File: frontend/src/components/SeedlotRegistrationBreadcrumb/index.tsx [hunk 1]
```diff
@@ -0,0 +1,42 @@
+import React from 'react';
```
Comment (mgaseta) [inline frontend/src/components/SeedlotRegistrationBreadcrumb/index.tsx:1]: Nice work, but how about making this component work for all breadcrumbs?
You can create a type with display name and path and pass to the component an array of this new type, then map this array and create the breadcrumb. (Just a way to do it, there are probably others)

File: frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss [hunk 2]
```diff
@@ -0,0 +1,18 @@
+@use '@bcgov-nr/nr-theme/design-tokens/variables.scss' as vars;
+
+  .overflow-menu-container {
+    display: none;
+  }
```
Comment (mgaseta) [inline frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss:5]: Adjust indentation here.

File: frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss [hunk 3]
```diff
@@ -0,0 +1,18 @@
+@use '@bcgov-nr/nr-theme/design-tokens/variables.scss' as vars;
+
```
Comment (mgaseta) [inline frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss:2]: Also, add a new parent class to these styles, so we can make sure the styles are only being applied to this component.

File: frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+  }
+
+@media only screen and (max-width: 320px) {
+  .overflow-breadcrumb {
+    display: none;
+  }
+  .overflow-menu-container {
+    display: flex;
+  }
+  .bx--breadcrumb{
```
Comment (mgaseta) [inline frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss:14]: Change `bx` to use the var from design token variables you imported.

File: frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+    display: flex;
+    flex-wrap: wrap;
+  }
+}
```
Comment (mgaseta) [inline frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss:18]: Add new line at EOF.

File: frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx [hunk 6]
```diff
@@ -88,6 +88,7 @@ import {
 } from './constants';
 
 import './styles.scss';
+import SeedlotRegistrationBreadcrumb from '../../../components/SeedlotRegistrationBreadcrumb';
```
Comment (mgaseta) [inline frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx:91]: Add this import with the other component imports, should be a few lines up.

**Review by mgaseta — CHANGES_REQUESTED** [review]
Nice job!
Added a some comments to improve the new component and other small fixes.

File: frontend/src/components/SeedlotRegistrationBreadcrumb/index.tsx (hunk 1 above)
Comment (ArthurEncr) [reply frontend/src/components/SeedlotRegistrationBreadcrumb/index.tsx:1]: Right! im going to start to work on that! :)

**Comment by ArthurEncr** [comment]
**New component called "BCBreadcrumb" Created!** 
_Behavior:_ An array with all breadcrumbs (with respective names and paths) must be passed through props to the component. On mobile devices, all breadcrumb items that are not the first and last will enter the overflow menu.

File: frontend/src/components/BCBreadcrumb/index.tsx [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+
+interface BCBreadcrumbProps {
+  breadcrumbData:
+    {
+      name: string,
+      path: string
+    }[]  
+}
+
+const BCBreadcrumb = ({breadcrumbData}:BCBreadcrumbProps) => {
```
Comment (mgaseta) [inline frontend/src/components/BCBreadcrumb/index.tsx:19]: Change the name here, no need for the `BC` prefix (maybe something like `DisplayBreadcrumb`), also add spaces between the `{` and `breadcrumbData`.

File: frontend/src/components/BCBreadcrumb/index.tsx [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+  const navigate = useNavigate();
+
+  const lastBreadcrumb = breadcrumbData.length - 1
```
Comment (mgaseta) [inline frontend/src/components/BCBreadcrumb/index.tsx:22]: Add `;`

File: frontend/src/components/BCBreadcrumb/index.tsx [hunk 9]
```diff
@@ -0,0 +1,78 @@
...
+  const overflowData = breadcrumbData.slice(1, lastBreadcrumb)
```
Comment (mgaseta) [inline frontend/src/components/BCBreadcrumb/index.tsx:23]: Add `;`

File: frontend/src/components/BCBreadcrumb/index.tsx [hunk 10]
```diff
@@ -0,0 +1,78 @@
...
+
+  if (breadcrumbData.length >= 3) {
```
Comment (mgaseta) [inline frontend/src/components/BCBreadcrumb/index.tsx:25]: I don't think this if needs to be here, add this validation as a ternary operation inside the breadcrumb component.
Also, there are a lot of indentation issues on these tags... Please attend to them.

File: frontend/src/components/BCBreadcrumb/index.tsx [hunk 11]
```diff
@@ -0,0 +1,78 @@
...
+              key={breadcrumb.name}
+            >
+              {breadcrumb.name}
+            </BreadcrumbItem>
+        ))}
+        </Breadcrumb>
+      </div>
+    )
+  }
+  ;
```
Comment (mgaseta) [inline frontend/src/components/BCBreadcrumb/index.tsx:75]: ???

File: frontend/src/views/Seedlot/EditAClassApplication/index.tsx [hunk 12]
```diff
@@ -150,20 +149,22 @@ const EditAClassApplication = () => {
...
+  { name: "Seedlots",
+    path: `${PathConstants.SEEDLOTS}`
+  },
+  { name: "My seedlots",
+    path: `${PathConstants.MY_SEEDLOTS}`
+  },
+  { name: `Seedlot ${seedlotNumber}`,
+    path: `${addParamToPath(PathConstants.SEEDLOT_DETAILS, seedlotNumber ?? '')}`
+  }
+]
```
Comment (mgaseta) [inline frontend/src/views/Seedlot/EditAClassApplication/index.tsx:162]: Missing `;` and wrong indentation.

File: frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx [hunk 13]
```diff
@@ -455,6 +456,18 @@ const SeedlotRegistrationForm = () => {
...
+      path: `${PathConstants.SEEDLOTS}`
+    },
+    { name: "My seedlots",
+      path: `${PathConstants.MY_SEEDLOTS}`
+    },
+    { name: `Seedlot ${seedlotNumber}`,
+      path: `${addParamToPath(PathConstants.SEEDLOT_DETAILS, seedlotNumber ?? '')}`
+    }
+  ] 
+
```
Comment (mgaseta) [inline frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx:470]: Missing `;` and wrong indentation.

File: frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx [hunk 14]
```diff
@@ -96,6 +96,7 @@ import {
 } from './constants';
 
 import './styles.scss';
+import BCBreadcrumb from '../../../components/BCBreadcrumb';
```
Comment (mgaseta) [inline frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx:99]: Change this import to a few lines up (with the other component imports).

**Review by mgaseta — CHANGES_REQUESTED** [review]
Thanks for the changes!
Added some markups.
Also, a lot of these issues are listed on the IDE as errors, maybe something with your IDE or with ESLint? We can take a look at it if you want.

File: frontend/src/views/Seedlot/EditAClassApplication/index.tsx [hunk 15]
```diff
@@ -150,20 +149,22 @@ const EditAClassApplication = () => {
...
-            Seedlots
-          </BreadcrumbItem>
-          <BreadcrumbItem onClick={() => navigate(PathConstants.MY_SEEDLOTS)}>
-            My seedlots
-          </BreadcrumbItem>
-          <BreadcrumbItem onClick={() => navigate(addParamToPath(PathConstants.SEEDLOT_DETAILS, seedlotNumber ?? ''))}>
-            {`Seedlot ${seedlotNumber}`}
-          </BreadcrumbItem>
-        </Breadcrumb>
+        <BCBreadcrumb breadcrumbData={EditAClassApplicationBreadcrumbs}/>
```
Comment (mgaseta) [inline frontend/src/views/Seedlot/EditAClassApplication/index.tsx:167]: Missing space between last prop and `/>`

File: frontend/src/views/Seedlot/EditAClassApplication/index.tsx [hunk 16]
```diff
@@ -150,20 +149,25 @@ const EditAClassApplication = () => {
...
+    },
+    {
+      name: 'My seedlots',
+      path: `${PathConstants.MY_SEEDLOTS}`
+    },
+    {
+      name: `Seedlot ${seedlotNumber}`,
+      path: `${addParamToPath(PathConstants.SEEDLOT_DETAILS, seedlotNumber ?? '')}`
+    }
+  ];
```
Comment (mgaseta) [inline frontend/src/views/Seedlot/EditAClassApplication/index.tsx:165]: You can add this const to a `constant.ts` file.

File: frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx [hunk 17]
```diff
@@ -455,6 +454,21 @@ const SeedlotRegistrationForm = () => {
...
+    },
+    {
+      name: 'My seedlots',
+      path: `${PathConstants.MY_SEEDLOTS}`
+    },
+    {
+      name: `Seedlot ${seedlotNumber}`,
+      path: `${addParamToPath(PathConstants.SEEDLOT_DETAILS, seedlotNumber ?? '')}`
+    }
+  ];
```
Comment (mgaseta) [inline frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx:470]: You can add this const to a `constant.ts` file too.
Also, change the name of the const to something more related to the component.

File: frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx [hunk 18]
```diff
@@ -42,6 +40,7 @@ import OrchardStep from '../../../components/SeedlotRegistrationSteps/OrchardSte
 import ParentTreeStep from '../../../components/SeedlotRegistrationSteps/ParentTreeStep';
 import ExtractionAndStorage from '../../../components/SeedlotRegistrationSteps/ExtractionAndStorageStep';
 import SubmitModal from '../../../components/SeedlotRegistrationSteps/SubmitModal';
+import DisplayBredcrumb from '../../../components/DisplayBreadcrumb';
```
Comment (mgaseta) [inline frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx:43]: Import name is wrong, it'll work because you are exporting default on the component, but for better consistence, use the correct name.

File: frontend/src/components/DisplayBreadcrumb/index.tsx [hunk 19]
```diff
@@ -0,0 +1,65 @@
...
+                <BreadcrumbItem
+                  onClick={() => navigate(breadcrumb.path)}
+                  key={breadcrumb.name}
+                >
+                  {breadcrumb.name}
+                </BreadcrumbItem>
+              ))}
+            </OverflowMenu>
+          </BreadcrumbItem>
+        ) : null}
```
Comment (mgaseta) [inline frontend/src/components/DisplayBreadcrumb/index.tsx:54]: I don't think that you need these two ternary checks, maybe there is a way to transform them into a single one? This way we can also avoid to use styles like `display: none` maybe we can discuss that over a call or in the dev collab meeting.

File: frontend/src/components/DisplayBreadcrumb/index.tsx [hunk 20]
```diff
@@ -0,0 +1,65 @@
...
+      name: string,
+      path: string
+    }[];
+}
+
+const DisplayBreadcrumb = ({ breadcrumbData }:DisplayBreadcrumbProps) => {
+  const navigate = useNavigate();
+
+  const lastBreadcrumb = breadcrumbData.length - 1;
+  const overflowData = breadcrumbData.slice(1, lastBreadcrumb);
```
Comment (mgaseta) [inline frontend/src/components/DisplayBreadcrumb/index.tsx:25]: Maybe changing the name of this variable is a good idea, most of the times it won't be related to overflow data.

**Review by mgaseta — CHANGES_REQUESTED** [review]
Waaaaay better, nice that you fixed your IDE issues.
Added only a few more mark ups.

**Review by RMCampos — APPROVED** [review]
Very nice job! 💯 

Regarding Matheus's comment, all good.

File: frontend/src/components/DisplayBreadcrumb/index.tsx [hunk 21]
```diff
@@ -0,0 +1,66 @@
...
+
+  const lastBreadcrumb = breadcrumbData.length - 1;
+  const middleBreadcrumbs = breadcrumbData.slice(1, lastBreadcrumb);
+  return (
+    <div className="breadcrumbs-container">
+      <Breadcrumb>
+        <BreadcrumbItem onClick={() => navigate(breadcrumbData[0].path)}>
+          {breadcrumbData[0].name}
+        </BreadcrumbItem>
+        {(breadcrumbData.length >= 3 && window.innerWidth <= 671)
```
[the remark this answers is not in the document]
Comment (ArthurEncr) [reply frontend/src/components/DisplayBreadcrumb/index.tsx:32]: Before I was using 320px there, but Matheus told me to count the values below the medium size screen (672) as small

File: frontend/src/components/DisplayBreadcrumb/index.tsx [hunk 22]
```diff
@@ -0,0 +1,66 @@
...
+import { useNavigate } from 'react-router-dom';
+
+import './styles.scss';
+
+interface DisplayBreadcrumbProps {
+  breadcrumbData:
+    {
+      name: string,
+      path: string
+    }[];
```
[the remark this answers is not in the document]
Comment (ArthurEncr) [reply frontend/src/components/DisplayBreadcrumb/index.tsx:18]: OK

File: frontend/src/components/DisplayBreadcrumb/styles.scss [hunk 23]
```diff
@@ -0,0 +1,13 @@
...
+  @media only screen and (max-width: 320px) {
+    .overflow-menu-container {
+      display: flex;
+    }
+    .#{vars.$bcgov-prefix}--breadcrumb{
+      display: flex;
+      flex-wrap: wrap;
+    }
+  }
+}
```
[the remark this answers is not in the document]
Comment (ArthurEncr) [reply frontend/src/components/DisplayBreadcrumb/styles.scss:13]: I'm using ".#{vars.$bcgov-prefix}--breadcrumb" to change the styles, because some styles come by default in carbon components and I wanted to change this behavior. I'm not sure how to use the grid system to have this same effect.
​

[the remark this answers is not in the document]
Comment (craigyu) [reply frontend/src/components/DisplayBreadcrumb/styles.scss:13]: I see, you're right, please disregard this comment.

[the remark this answers is not in the document]
Comment (DerekRoberts) [reply frontend/src/components/DisplayBreadcrumb/styles.scss:13]: And this comment too!  Absolutely no value!  ;)

[the remark this answers is not in the document]
Comment (craigyu) [reply frontend/src/components/DisplayBreadcrumb/styles.scss]: the problem with this is that the default behaviour will happen again in medium sized window. A style applied to the entire component will be just fine.

File: frontend/src/components/SeedlotRegistrationProgress/index.tsx [hunk 24]
```diff
@@ -23,6 +25,7 @@ const SeedlotRegistrationProgress = ({
     className={className}
     spaceEqually
     onChange={interactFunction ?? null}
+    vertical={window.innerWidth <= SMALL_SCREEN_WIDTH}
```
Comment (craigyu) [inline frontend/src/components/SeedlotRegistrationProgress/index.tsx:28]: this doesn't actually work, will update this to use the hook I created.

**Review by craigyu — APPROVED** [review]

File: frontend/src/components/Breadcrumbs/constants.ts [hunk 25]
```diff
@@ -0,0 +1,3 @@
+export const DEFAULT_MAX_CRUMBS = 4;
```
Comment (mgaseta) [inline frontend/src/components/Breadcrumbs/constants.ts:1]: Do we need a default for max crumbs? What if a page got more than 4? Or is this a design rule?

File: frontend/src/components/Breadcrumbs/styles.scss [hunk 26]
```diff
@@ -0,0 +1,8 @@
+@use '@bcgov-nr/nr-theme/design-tokens/variables.scss' as vars;
+
+.breadcrumbs-container {
+  .#{vars.$bcgov-prefix}--breadcrumb{
```
Comment (mgaseta) [inline frontend/src/components/Breadcrumbs/styles.scss:4]: Sorry for nitpicking, but there is a missing space between the class and the `{`.

File: frontend/src/hooks/UseWindowSize.tsx
Comment (mgaseta) [inline frontend/src/hooks/UseWindowSize.tsx:1]: Nice hook!

File: frontend/src/views/Seedlot/EditAClassApplication/utils.ts
Comment (mgaseta) [inline frontend/src/views/Seedlot/EditAClassApplication/utils.ts:1]: Why use an utils file here? The function will return pretty much the same result, shouldn't this be on constants.ts?

**Review by mgaseta — APPROVED** [review]
Great job @craigyu and @ArthurEncr !
Added only a few non-blocking questions.

File: frontend/src/components/Breadcrumbs/constants.ts (hunk 25 above)
Comment (craigyu) [reply frontend/src/components/Breadcrumbs/constants.ts:1]: there's no rule for this, but if we want to use overflow menu we need to have some sort of upper limit, carbon design guide says breadcrumbs should not be more than 1 line, so I made this one up. 
In practicality this means more than 4 crumbs will have their middle ones sandwiched between 2 at the start and 2 at the end.

**Review by mgaseta — CHANGES_REQUESTED** [review]
Actually... It doesn't seem to be working properly.
Here is a print of a small screen:
Screenshot from 2024-02-06 14-57-35
The progress bar is not on vertical...

File: frontend/src/views/Seedlot/EditAClassApplication/utils.ts
Comment (craigyu) [reply frontend/src/views/Seedlot/EditAClassApplication/utils.ts:1]: My argument is that it is a function that returns an object depending on a parameter, so strictly speaking it is not a constant.

File: frontend/src/components/Breadcrumbs/constants.ts (hunk 25 above)
Comment (mgaseta) [reply frontend/src/components/Breadcrumbs/constants.ts:1]: Hmmm, ok that sounds good to me. Thanks for the clarification s2!

**Comment by craigyu** [comment]
> Actually... It doesn't seem to be working properly. Here is a print of a small screen: Screenshot from 2024-02-06 14-57-35 The progress bar is not on vertical...

I just replaced Arthur's code here with the hook I made, I will update it to different limit.
image

File: frontend/src/views/Seedlot/EditAClassApplication/utils.ts
Comment (mgaseta) [reply frontend/src/views/Seedlot/EditAClassApplication/utils.ts:1]: Yeah, that do makes sense... It's just weird to see a function that returns almost exactly the same thing every time on the `utils.ts`. But that's ok, I will get use to it.

**Review by mgaseta — APPROVED** [review]
Approved!!
(Sorry for taking so long with this one).

**Review by mgaseta — APPROVED** [review]
Nice new changes!
Added only a small markup.

File: frontend/src/views/Seedlot/SeedlotRegFormClassA/styles.scss [hunk 27]
```diff
@@ -144,15 +140,16 @@
       align-items: center;
       flex-direction: row;
 
-      .bx--actionable-notification__action-button{
+      .bx--actionable-notification__action-button {
```
[the remark this answers is not in the document]
Comment (craigyu) [reply frontend/src/views/Seedlot/SeedlotRegFormClassA/styles.scss:143]: auto formatting sold me out
