### PR TITLE
fix: ui issues and improvements pt. 1

### LINKED ISSUE #908: Typo on step 6 of seedlot registration
On the "Extraction and storage" step of seedlot registration in TEST, there is a sentence that appears below the heading "Extraction information" and again under "Temporary seed storage"

"Enter the seed storage agency information and storage's star and end dates for this seedlot"

should instead read:

"Enter the seed storage agency information and storage's start and end dates for this seedlot"

(changing 'star' to 'start')

### LINKED ISSUE #1345: Acronym display bug
the agency acronym input display different text when in different mode, this bug might appears in other screens as well.

Image

### LINKED ISSUE #1421: text update found by kevin
Update some text listed in #1272 

1. 
> Register an a-class seedlot:
> 
> 
> 
> Image
> 
> 
> 
> - [x] I would remove the subheading "Register a new A-class seedlot" (redundant with heading above) 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226543704)_

2. 
> A-class seedlot created:
> 
> 
> 
> 
> 
> 
> 
> Image
> 
> 
> 
> - [x] Change "Seedlot's main screen" to:
> 
> "Seedlots main screen"
> 
> (removing apostrophe) 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226546586)_

3. 
> Client search modal:
> 
> 
> 
> 
> 
> 
> 
> Image
> 
> 
> 
> "To view more information about the client, you can go to client search screen."
> 
> 
> 
> - [x] change to:
> 
> 
> 
> "To view more information about the client, go to the client search screen." 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226550062)_

4. 
> Collection methods:
> 
> 
> 
> 
> 
> 
> 
> Image
> 
> 
> 
> - [ ] Would it make sense to list the collection methods in alphabetical order? 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226555719)_

5. 
> Cone and pollen count:
> 
> 
> 
> 
> 
> 
> 
> Image
> 
> 
> 
> "Enter the estimative of Cone and pollen count for the orchard's seedlot (*required)"
> 
> I would change it to:
> 
> - [x] "Enter the cone and pollen count estimate for the orchard's seedlot"
> 
> 
> 
> 
> 
> SMP success on parent:
> 
> 
> 
> 
> 
> 
> 
> Image
> 
> 
> 
> "Enter the same SMP success on parent or Non-orchard pollent contaminant to all parent trees"
> 
> 
> 
> - [x] I would change "Non-orchard" to "non-orchard"
> 
> 
> 
> 
> 
> Calculation of SMP mix:
> 
> 
> 
> 
> 
> 
> 
> Image
> 
> 
> 
> "Enter the estimative of SMP success for the orchard's seedlot"
> 
> I would change to:
> 
> - [x] "Enter the SMP success estimate for the orchard's seedlot" 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226559587)_

6. 
> File upload:
> 
> 
> 
> 
> 
> 
> 
> Image
> 
> 
> 
> "Note: When uploading a file all previously filled data within the table will be replaced." 
> 
> Please change to:
> 
> - [x] "Note: When uploading a file, all previously filled data in the table will be replaced." 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226560028)_

7. 
> Breeding value of SMP mix used
> Image
> 
> The subheading is redundant here in my opinion. I would remove that and update the heading to read:
> 
> "Breeding value of SMP mix used on parent" 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226561880)_

8. 
> 
> 
> Image
> 
> "SMP Mix geospatial summary"
> 
> Please change to:
> 
> - [x] "SMP mix geospatial summary"
> 
>  

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226562613)_

9. - [ ]
> Step 6:
> 
> 
> 
> Image
> 
> "Enter the extractory agency information and extraction's star and end dates for this seedlot"
> 
> change to:
> 
> - [x] "Enter the extractory agency information and extraction's start and end dates for this seedlot"
> 
> (change "star" to "start")
> 
> 
> 
> 
> 
> Image
> 
> "Enter the seed storage agency information and storage's star and end dates for this seedlot"
> 
> change to:
> 
> - [x] "Enter the seed storage agency information and storage's start and end dates for this seedlot"
> 
> (change "star" to "start")
> 
>  

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226565030)_

10. 
> 
> 
> Image
> 
> 
> 
> - [x] Change instances of "Tree Seed Center" to instead read "Tree Seed Centre"
> 
> 
> 
> This one's a bit tricky, but in Canada we use the French spelling of center, so it should actually be "Tree Seed Centre" instead of "Tree Seed Center"
> 
> 
> 
> When Tree Seed Centre comes up in data queries, it is spelled the French way in the database, so it would be nice to keep consistent.
> 
> 
> 
> Hopefully this is more of a find-and-replace kind of function in the front-end 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226566984)_

11.
> Declaration modal:
> 
> 
> 
> Image
> 
> 
> 
> Declaration:
> 
> "Please, be sure to review the content and check if everything is correct with your seedlot registration.
> 
> Go to first step and review the form."
> 
> 
> 
> Please change to:
> 
> - [x] "Please review this form to ensure the information is correct for this seedlot registration.
> 
> Click here to go back to the first step."
> 
> 
> 
> 
> 
> And then have "Click here" link to the first step in the form 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226571645)_

### PR DESCRIPTION
**Pull request by mgaseta**
# Description
Closes #1345
Closes #908 
Closes points 1, 3 and 5 from: #1386 
Closes [this](https://github.com/bcgov/nr-spar/issues/1388#issuecomment-2225669553) and [this](https://github.com/bcgov/nr-spar/issues/1388#issuecomment-2225759420) from #1388
Also, fixes the wrong subtitles when reviewing the orchard step.

#### New
- New scroll to the top component.

#### Changed
- Texts and styles

#### Removed
- Nothing :)

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-spar-25-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1425-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1425-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-spar/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml)

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-spar-25-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1425-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1425-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-spar/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml)

### CODE REVIEW

**Review by RMCampos — APPROVED** [review]
Great job 🥇

File: frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx [hunk 1]
```diff
@@ -137,204 +138,209 @@ const CollectionStep = ({ isReview }: CollectionStepProps) => {
...
-      <Row className="collection-step-row">
-        <Column className="section-title" sm={4} md={8} lg={16} xlg={16}>
-          <h2>{fieldsConfig.titleSection.title}</h2>
-          {
-            isReview
-              ? null
-              : <Subtitle text={fieldsConfig.titleSection.subtitle} />
+    <>
+      {
+        !isReview ? (<ScrollToTop />) : null
```
Comment (craigyu) [inline frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx:143]: Can we add a prop `enabled` to <ScrollToTop />, it should default to true, so that:
1. `<ScrollToTop />` works
2. `<ScrollToTop enabled={!isReview} />` works

this way we can avoid all the ternary, what do you think?

Also, can we not have this under <FlexGrid>? does it only work if it's outside?

**Review by craigyu — APPROVED** [review]

File: frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx (hunk 1 above)
Comment (mgaseta) [reply frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx]: Great idea, implemented here: https://github.com/bcgov/nr-spar/pull/1425/commits/8aae4ece6373362a25a94d4ca637ec2155d8c490
