### PR TITLE
fix: click on overlay closes menus

### LINKED ISSUE #726: Click on overlay should close side menus
Image

Image

Clicking on the overlay (grey) area should close the side menu but it doesn't work.

### PR DESCRIPTION
**Pull request by ArthurEncr**
# Description
Closes #726 

#### New
- Overlay fixed. Now when it's clicked should closes the side menus.

### How was this tested?
- [x] 🧠 Not needed
- [ ] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Frontend](https://nr-spar-28-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-28-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-28-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

### CODE REVIEW

File: frontend/src/components/BCHeader/index.tsx [hunk 1]
```diff
@@ -60,6 +60,10 @@ const BCHeader = () => {
     });
   };
 
+  const handleClosePanel = () => {
+    if (rightPanel.notifications === true) { closeRightPanel('notifications'); } else { closeRightPanel('myProfile'); }
```
Comment (mgaseta) [inline frontend/src/components/BCHeader/index.tsx:64]: Use multiple lines to declare this if, it is more readable and keeps the code pattern.

File: frontend/src/components/BCHeader/index.tsx [hunk 2]
```diff
@@ -69,6 +73,9 @@ const BCHeader = () => {
           aria-label={componentTexts.completeTitle}
           className="spar-header"
           data-testid="header"
+          onClick={
+                isSideNavExpanded === true ? onClickSideNavExpand : null
```
Comment (mgaseta) [inline frontend/src/components/BCHeader/index.tsx:77]: Tab is looking odd here... The content should be only a tab (2 spaces) ahead of the `onClick` declaration, same goes for the closing bracket, it should on the same column of the `onClick`.

File: frontend/src/components/BCHeader/index.tsx [hunk 3]
```diff
@@ -129,7 +136,17 @@ const BCHeader = () => {
...
-              ? <div className="overlay-element" />
+              ? (
+                <div
+                  className="overlay-element"
+                  role="button"
+                  tabIndex={0}
+                  aria-label="close right panel"
+                  onKeyDown={handleClosePanel}
+                  onClick={handleClosePanel}
+
```
Comment (mgaseta) [inline frontend/src/components/BCHeader/index.tsx:147]: Remove this empty line.

File: frontend/src/components/BCHeader/index.tsx [hunk 4]
```diff
@@ -129,7 +136,17 @@ const BCHeader = () => {
...
           {
             overlay
-              ? <div className="overlay-element" />
+              ? (
+                <div
+                  className="overlay-element"
+                  role="button"
+                  tabIndex={0}
+                  aria-label="close right panel"
+                  onKeyDown={handleClosePanel}
```
Comment (mgaseta) [inline frontend/src/components/BCHeader/index.tsx:145]: On `onKeyDown` event, we need to make sure that the only interactive keys are space and enter, assistive tools often uses other keys to navigate thru the page and these keys should not interact with the page.

**Review by mgaseta — CHANGES_REQUESTED** [review]
Nice job! :100: :1st_place_medal: 

Added only a few markups.

Maybe not necessary for now, but pressing the `Esc` key should also close the menus, try looking that up and if it's easy enough use this task to implement it, if not, we can create a new one.

File: frontend/src/components/BCHeader/index.tsx (hunk 1 above)
Comment (RMCampos) [inline frontend/src/components/BCHeader/index.tsx:64]: nitpick: I think you can safely replace `if (rightPanel.notifications === true)` by `if(rightPanel.notifications)` since TS is more reliable than JS 😄

File: frontend/src/components/BCHeader/index.tsx (hunk 2 above)
Comment (RMCampos) [inline frontend/src/components/BCHeader/index.tsx:77]: nitpick: same here. No need to compare with `true` since `isSideNavExpanded` is a boolean. Wait.. That's an `any` 😢 

Maybe we improve this piece of code, and replace `{ isSideNavExpanded, onClickSideNavExpand }: any` by `{ isSideNavExpanded: boolean, onClickSideNavExpand: Function }`? Or a simple interface.

**Review by RMCampos — CHANGES_REQUESTED** [review]
Great job! Thank you 💯 . I left two small requests, though. :-)

File: frontend/src/components/BCHeader/index.tsx [hunk 5]
```diff
@@ -60,15 +60,33 @@ const BCHeader = () => {
...
+    }
+  };
+
   const navigate = useNavigate();
 
+  interface HearderContainerProps {
+  isSideNavExpanded: boolean,
+  onClickSideNavExpand: Function
+}
+
```
Comment (craigyu) [inline frontend/src/components/BCHeader/index.tsx:81]: Put this inside the `definitions.ts` file

**Review by craigyu — CHANGES_REQUESTED** [review]
Working nicely! 

I strongly recommend you to start using the auto-indent function on VSC, it will format things for you.
https://code.visualstudio.com/docs/editor/codebasics#_formatting
The image below shows the edits you'll need to make, but it's a non-issue. 
image

File: frontend/src/components/BCHeader/index.tsx [hunk 6]
```diff
@@ -60,15 +60,33 @@ const BCHeader = () => {
...
   return (
     <HeaderContainer
-      render={({ isSideNavExpanded, onClickSideNavExpand }: any) => (
+      render={({ isSideNavExpanded, onClickSideNavExpand }: HearderContainerProps) => (
         <Header
           aria-label={componentTexts.completeTitle}
           className="spar-header"
           data-testid="header"
+          onClick={isSideNavExpanded === true ? onClickSideNavExpand : null}
```
Comment (mgaseta) [inline frontend/src/components/BCHeader/index.tsx:89]: You can safely remove the `=== true`, the variable type is a `boolean`, so there is no need for it.

File: frontend/src/components/BCHeader/index.tsx [hunk 7]
```diff
@@ -138,6 +165,9 @@ const BCHeader = () => {
             aria-label={componentTexts.sideMenuAriaLabel}
             inert={undefined}
             className="spar-side-nav"
+            onClick={
+                isSideNavExpanded === true ? onClickSideNavExpand : null
```
Comment (mgaseta) [inline frontend/src/components/BCHeader/index.tsx:169]: Same here.

**Review by mgaseta — APPROVED** [review]
LGTM! :100: :1st_place_medal: 
Added only 2 non-blocking enhancements.

**Review by craigyu — APPROVED** [review]

**Review by RMCampos — APPROVED** [review]
LGTM
