### PR TITLE
fix: 1175 refactor client and location logic

### LINKED ISSUE #1175: Refactor client and location logic
The current implementation of the client and location logic is causing a bug on the review process, this refactor is to fix that issue and also make the frontend more efficient.

To reproduce the issue:
1. After registering a seedlot, go to the review page
2. Click the `Edit seedlot` button
3. On the Collection section, try to edit agency field
4. The input maybe wrongly filled (intermittent issue, probably due to async calls)
5. Edit won't be possible

Screenshot from 2024-05-23 15-14-48

### PR DESCRIPTION
**Pull request by mgaseta**
# Description
Closes #1175

#### New
- New type to deal with forest clients

#### Changed
- Updated the request for forest clients and mapped them, so it's easier to fill form data

#### Removed
- No longer necessary API calls

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-spar-27-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1177-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1177-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-spar/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml)

### CODE REVIEW

File: frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/index.tsx [hunk 1]
```diff
@@ -119,31 +117,14 @@ const OwnershipStep = () => {
...
-        queryFn: () => getForestClientByNumberOrAcronym(client),
-        enabled: isFormSubmitted,
-        staleTime: THREE_HOURS,
-        cacheTime: THREE_HALF_HOURS
-      })
-    )
-  });
-
-  const qc = useQueryClient();
-
```
Comment (craigyu) [inline frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/index.tsx:135]: nice!

**Review by RMCampos — APPROVED** [review]
Great job! Working like a charm 💯
